### PR TITLE
Add xGen NX-64IP Support

### PR DESCRIPTION
**Pull request by caronc**
## Description:
**Related issue (if applicable):** [ha-ultrasync/issues/3](https://github.com/caronc/ha-ultrasync/issues/3)

Add support for xGen UltraSync Device.

### CODE REVIEW

**Comment by caronc** [comment]
@33Fraise33 I'm just going to pull you over to this ticket for a wee bit as it's the core of the Home Assistant Integration.

Can you do me a small favour and check out this branch and perform a `--debug-dump` for me? The index.html you already provided me in the other ticket was a great start!  I just need more details to get the rest done.  Here is basically what I need you to do (i apologize as it's a wee bit complicated, but I promise the reward is getting your alarm panel added into Home assistant at the end of the day).

The first thing to do is just create a text file.  You can use `notepad.exe` if you're in Windows, or any editor of your choice in Linux/Mac.  The text file just has to have 3 entries in it; this will be your config file to use this script.  It's the same things you  need to provide Home Assistant in order for it to work there too:
```yaml
# the ip to your xGen Security Panel
host: 192.168.0.30
# The Web User ID you use to log into it with:
user: My Username
# Your Pin:
pin: 1234
```

, check out this branch: **xgen-nx64ip-support**; you can do this in several ways an capture a `--debug-dump` for me:
1. Use **git**:
    ```bash
    # Clone the repository:
    git clone https://github.com/caronc/ultrasync.git

    # Change to the directory you just cloned to (with respect to the above, you'd
    # have created an ultrasync directory):
    cd ultrasync

    # Then switch to this branch:
    git checkout xgen-nx64ip-support

    # Now call the ultrasync tool referencing your configuration file you created
    # along with --debug-dump
    bin/ultrasync -c /path/to/config --debug-dump
    ```
2. Use `pip` if you already have Python (v3) installed on your pc:
    ```bash
    # Install our branch:
    pip install git+https://github.com/caronc/ultrasync.git@xgen-nx64ip-support

    # Now call the ultrasync tool referencing your configuration file you created
    # along with --debug-dump
    bin/ultrasync -c /path/to/config --debug-dump
    ```
3. Just [download a the zip file of this current branch with your browser](https://github.com/caronc/ultrasync/archive/master.zip), unzip it and then from a command line:
    ```bash
    # Change to the directory you just unzipped your content to:
    cd ultrasync

    # Now call the ultrasync tool referencing your configuration file you created
    # along with --debug-dump
    bin/ultrasync -c /path/to/config --debug-dump
    ```

This will produce a zip file you can pass back to me with slightly more files then the ones you already shared. It will allow me to see how the zone information an update details are controlled using your version of the UltraSync device.

Also, all UltraSync devices only allow 1 login per user at a time.  So create a separate account for your Home Assistant user (and these tests).  Also, if your Home Assistant configuration is still set up.  Remove it (otherwise Home Assistant will be competing with your testing as it will continuously try to log in over and over again) while you help me out here :slightly_smiling_face: .  Hopefully this all makes sense!

Please let me know if you have any questions or concerns or are having any issues with the info above.

**Comment by 33Fraise33** [comment]
Hi ,

I had to use pip as otherwise modules were not installing. 

This is the output in my terminal (running on Arch)
```
Creating debug archive  [###---------------------------------]    9%  00:00:222020-12-23 11:26:50,864 - ERROR - Failed to query http://172.16.50.7/muser/config2.htm
Creating debug archive  [############------------------------]   33%  00:00:152020-12-23 11:26:54,388 - ERROR - Failed to query http://172.16.50.7/protect/randmenu.xml
Creating debug archive  [##################------------------]   52%  00:00:112020-12-23 11:27:03,611 - ERROR - Failed to query http://172.16.50.7/protect/randmenu.xml
2020-12-23 11:27:04,582 - ERROR - Failed to query http://172.16.50.7/protect/randmenu.xml
2020-12-23 11:27:06,219 - ERROR - Failed to query http://172.16.50.7/protect/randmenu.xml
Creating debug archive  [####################################]  100%      
```

[20201223112647.ultrasync-dump.zip](https://github.com/caronc/ultrasync/files/5734630/20201223112647.ultrasync-dump.zip)

**Comment by caronc** [comment]
Thank you so much for the files! This is great!  Don't worry about the errors, if the file doesn't exist it's okay.  I got the main ones i needed.

One thing i notice is your panel has 2 areas defined (`SENSOREN` and `RAMEN EN DEUREN`, but only gets the status for one of them (`SENSOREN`).  I find that strange; Do you actually define 2 areas on your end? Or are you only using the first one?

**Comment by 33Fraise33** [comment]
Hello,

I did not install this and configure this so I don't understand the
complete setup. But
'sensoren' are wall sensors that capture motion. 'ramen en deuren' are
magnet contacts in windows and doors. I can arm and disarm them separately
which is handy as we have animals which might set of the sensors but not
the magnet contacts.

**Comment by caronc** [comment]
@33Fraise33,

The information you shared is great! I finally had a chance today to dig into the code.  I think I may have completed this request.

If you repeat the above steps to check out the branch again, actions like this *should* work for you:
```bash
# You should be be able to monitor your house:
ultrasync -c /path/to/config --watch

# You can arm/disarm your setup to this way:
ultrasync -c /path/to/config --scene stay
ultrasync -c /path/to/config --scene disarm
```

Let me know how it goes. If you get an error message, please share it too! :slightly_smiling_face: 

Good luck!

**Comment by 33Fraise33** [comment]
I upgrade with `pip install git+https://github.com/caronc/ultrasync.git@xgen-nx64ip-support
--upgrade`

When running watch I get the following error:
```
ultrasync -c ultrasync-config --watch
2021-01-02 12:22:56 [001] DEC INKOM               : Ready
2021-01-02 12:22:56 [001] DEC ZITRUIMTE           : Ready
2021-01-02 12:22:56 [001] RAAM ZITHOEK VOORAAN LINKS: Ready
2021-01-02 12:22:56 [001] RAAM ZITHOEK VOORAAN RECHTS: Ready
2021-01-02 12:22:56 [001] RAAM ZITHOEK ZIJKANT    : Ready
2021-01-02 12:22:56 [001] RAAM EETPLAATS ZIJKANT  : Ready
2021-01-02 12:22:56 [001] RAAM EETPLAATS VOORZIJDE: Ready
2021-01-02 12:22:56 [001] SCHUIFRAAM EETPLAATS    : Ready
2021-01-02 12:22:56 [001] VOORDEUR                : Ready
2021-01-02 12:22:56 [001] DEC KEUKEN              : Ready
2021-01-02 12:22:56 [001] ACHTERDEUR              : Ready
2021-01-02 12:22:56 [001] DEC WASPLAATS           : Ready
2021-01-02 12:22:56 [001] RAAM BADKAMER           : Ready
2021-01-02 12:22:56 [001] DEC NACHTHAL            : Ready
2021-01-02 12:22:56 [001] BUITENSIRENE            : Ready
2021-01-02 12:22:56 [022] SENSOREN                : Ready
2021-01-02 12:22:56 [000] RAMEN EN DEUREN         : Ready
---
Traceback (most recent call last):
  File "/home/gianni/.local/bin/ultrasync", line 33, in <module>
    sys.exit(load_entry_point('ultrasync==0.9.2', 'console_scripts', 'ultrasync')())
  File "/home/gianni/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/gianni/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/gianni/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gianni/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/gianni/.local/lib/python3.9/site-packages/ultrasync/cli.py", line 199, in main
    results = usync.details()
  File "/home/gianni/.local/lib/python3.9/site-packages/ultrasync/main.py", line 588, in details
    if not self.update(max_age_sec=max_age_sec):
  File "/home/gianni/.local/lib/python3.9/site-packages/ultrasync/main.py", line 573, in update
    if not self._sequence():
  File "/home/gianni/.local/lib/python3.9/site-packages/ultrasync/main.py", line 1736, in _sequence
    return getattr(self, '_{}_sequence'.format(self.vendor))()
AttributeError: 'UltraSync' object has no attribute '_xgen_sequence'

```

**Comment by caronc** [comment]
@33Fraise33, Thank you for your testing!  I was able to use your shared information to add more unit test coverage and I believe to have fixed the issue you brought forth.

Give it another go (grab the latest code again from the branch) and keep up the great work of informing me if anything goes wrong.

We're almost there i think! :+1: 

Chris

**Comment by 33Fraise33** [comment]
> @33Fraise33, Thank you for your testing! I was able to use your shared information to add more unit test coverage and I believe to have fixed the issue you brought forth.
> 
> Give it another go (grab the latest code again from the branch) and keep up the great work of informing me if anything goes wrong.
> 
> We're almost there i think! 
> 
> Chris

I just tested it again and my result still gives an error but a different one, do I need to provide the debug dump again or does this not have any extra information at this stage?

```
ultrasync -c ultrasync-config --watch -v
2021-01-05 07:47:09 [001] DEC INKOM               : Ready
2021-01-05 07:47:09 [001] DEC ZITRUIMTE           : Ready
2021-01-05 07:47:09 [001] RAAM ZITHOEK VOORAAN LINKS: Ready
2021-01-05 07:47:09 [001] RAAM ZITHOEK VOORAAN RECHTS: Ready
2021-01-05 07:47:09 [001] RAAM ZITHOEK ZIJKANT    : Ready
2021-01-05 07:47:09 [001] RAAM EETPLAATS ZIJKANT  : Ready
2021-01-05 07:47:09 [001] RAAM EETPLAATS VOORZIJDE: Ready
2021-01-05 07:47:09 [001] SCHUIFRAAM EETPLAATS    : Ready
2021-01-05 07:47:09 [001] VOORDEUR                : Ready
2021-01-05 07:47:09 [001] DEC KEUKEN              : Ready
2021-01-05 07:47:09 [001] ACHTERDEUR              : Ready
2021-01-05 07:47:09 [001] DEC WASPLAATS           : Ready
2021-01-05 07:47:09 [001] RAAM BADKAMER           : Ready
2021-01-05 07:47:09 [001] DEC NACHTHAL            : Ready
2021-01-05 07:47:09 [001] BUITENSIRENE            : Ready
2021-01-05 07:47:09 [011] SENSOREN                : Ready
2021-01-05 07:47:09 [000] RAMEN EN DEUREN         : Ready
---
2021-01-05 07:47:10,674 - ERROR - Could not retrieve alarm status

```

**Comment by caronc** [comment]
Hmm... I'll see if i can reproduce this and get back to you

**Comment by caronc** [comment]
@33Fraise33 I was able to reproduce your issue and i fixed it! :+1: 

When you have time, please rinse and repeat (checking out latest code and trying again). I'm almost certain we're almost there!

Also wave in front of your sensors while in `watch` mode.  Open a door, etc.  Trip your sensors and verify they're correctly being reported on screen.

Good luck!

Chris

**Comment by 33Fraise33** [comment]
It seems to work as expected now ;) how can I now integrate this in home assistant?

**Comment by caronc** [comment]
@33Fraise33 First off, thank you kindly for your donation.  I really appreciate it. :+1: :pray: 

I'll merge this into the master branch; I need to make it a release here and bump the version in ha-ultrasync to get the best results (it's as simple as updating your copy right from HACS). However, in the meantime if you can access the shell terminal of your Home Assistant setup, you can actually just install this branch (using `pip install git+https://github.com/caronc/ultrasync.git@xgen-nx64ip-support`) over-top of the version you've got and everything *should* just magically work.

On a side note, I'm learning of another xGen panel too called xGen v8 (have you heard of that? - [see here](https://community.home-assistant.io/t/interlogix-ultrasync/51464/131?u=l2g)).  The shared output he provided is actually very different then yours! This is the first UltraSync model I've seen that doesn't include the version and and type code in it's html body.  Anyway; not your problem, I'll figure it out.  I'll try to bump the version and get this release pushed soon though. I'll keep you posted.

**Pull request merged**
