### PR TITLE
Output Control Support (Hills Comnav)

### PR DESCRIPTION
**Pull request by Ay1tsMe**
## Description:
**Related issue (if applicable):** #https://github.com/caronc/ha-ultrasync/issues/13

Added support for output controls. Tested and working for the Hills Comnav. Possibly needs integration with other alarm systems, however I do not have any on hand to test with. 

Hoping this gets working and integrated within the ha-ultrasync wrapper.

### CODE REVIEW

**Comment by Ay1tsMe** [comment]
Documentation for output control can be removed.

**Comment by caronc** [comment]
There is a class variable you can access from everywhere to get you the alarm system being used.  You can see from many examples in the code where you can wrap `if` statements to ensure the actions you identified don't kick in for other alarms.

I think once you nail that, the people who've opened [ha-ultrasync/13](https://github.com/caronc/ha-ultrasync/issues/13) will be very happy of you!

**Comment by Ay1tsMe** [comment]
Okay, I adjusted the functions to check the vendor. Right now, only Hills Comnav is the supported vendor. I had a look through all the manuals for output control with each vendor and I could only find documentation on the Hills Comnav so I'm assuming that's the only vendor that supports it.

If not then it should be just as easy as changing the `if` statements to check for that vendor. Worst case scenario is they use a different `payload` format. 

I'm not sure if any adjustments will need to be done for the [Home Assistant Wrapper](https://github.com/caronc/ha-ultrasync) to support my changes. I think a new service will need to be created that calls the `set_output_control` function. Not sure If anything else needs to be done.

If you would like me to fix any code in this fork then let me know :)

**Comment by caronc** [comment]
I think you did a really good job; i can't spot anything unusual.  I assume you're also happy, everything is working for you as expected?

**Comment by Ay1tsMe** [comment]
Yep everything's working for me. I'm ready to merge. And then whatever needs to be done to make it work in home assistant I can also help you with 👍

**Comment by Ay1tsMe** [comment]
Also mentioned early, you can delete my readme changes from the main branch as they were just documentation for my understanding on the outputs.htm

**Pull request merged**
