### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by thanomichalis**
It solves the compatibility issue for Bypass/Unbypass zones for the COMNAV vendor. Ticket was opened here: https://github.com/caronc/ha-ultrasync/issues/23

## Description:
**Related issue (if applicable):** #

### CODE REVIEW

**Comment by chatziko** [comment]
The `state` variable (which decides whether to bypass or unbypass) is not used. Does this code work for both bypass and unbypass? (seems unlikely)

**Comment by caronc** [comment]
@chatziko I'm okay with merging this if this addresses the issues.  But can i also ask you to just roll back half of the changes you made where you put the code `if <your panel> and <another>` everywhere in your last integration... just change it back to you `<your panel>` so the others get the error that their panel isn't supported?

I recall you made the assumption both would work, but we ended up getting people messaging in that it didn't for the other.

Thoughts?

p.s. thank you for your contributions again! :rocket: :pray:

**Comment by chatziko** [comment]
I'm not sure I follow, from what I remember the very first PR originally assumend it works for other models, but you pointed it out and I changed it. My [actual commit](67af936b81b58251c45731128820bb760e9ac339) only works for `XGEN8`.

Then there was a [subsequent commit](13a74026bebedd1e4f435c1f56b71c6ac55630a3) by @isorin adding `ZEROWIRE`, I guess he tested it in his system.

Btw this PR likely works only for bypass, not unbypass (see my comment above). If it's indeed the case it should be fixed before merging.

**Comment by chatziko** [comment]
Cool.

@thanomichalis : can you test both bypass and unbypass? Likely one of the two won't work cause the `state` variable is not used, so the same command is sent to the alarm in both cases.

**Comment by thanomichalis** [comment]
@chatziko i am not sure i understand you correctly. I have just added the 5 lines with the elif and remove the comnav vendor from the else part. No other change have been made, in any file.
In any case offcourse it worked with the unbypass. I have already implemented it with mushroom template card, to conditionally call the service with a double tap to bypass the zone and with a single tap to unbypass.

`
type: custom:mushroom-template-card
primary: '{{state_attr(''sensor.home_alarm_zone1state'', ''friendly_name'')}}'
secondary: >-
  {{states('sensor.home_alarm_zone1state')}} 

  {% set zone = state_attr('sensor.home_alarm_zone1state',
  'bank_state')[3:4]|float %}

  {% if zone > 0 %} (Bypassed)

  {% endif %}
icon: mdi:door
layout: vertical
entity: sensor.home_alarm_zone1state
tap_action:
  action: call-service
  service: ultrasync.unbypass
  data:
    zone: 1
  target: {}
double_tap_action:
  action: call-service
  service: ultrasync.bypass
  data:
    zone: 1
  target: {}
multiline_secondary: false
icon_color: |-
  {% set state=states('sensor.home_alarm_zone1state') %}
  {% if state=='Ready' %} green
  {% else %} red
  {% endif %}
badge_icon: >-
  {% set zone = state_attr('sensor.home_alarm_zone1state',
  'bank_state')[3:4]|float %}

  {% if zone > 0 %} mdi:shield-alert

  {% endif %}
badge_color: >-
  {% set zone = state_attr('sensor.home_alarm_zone1state',
  'bank_state')[3:4]|float %}

  {% if zone > 0 %} amber

  {% endif %}
`

Is it a way to capture in log the call service, just for the records?

**Comment by chatziko** [comment]
What is weird is that both `ultrasync.unbypass` and `ultrasync.bypass` are sending the __exact same command__ to the alarm, based on your code. Maybe the command is __toggling__ the state? Try to call  `ultrasync.bypass` twice, what happens?

**Comment by thanomichalis** [comment]
You are correct. It is acting as toggle.

**Comment by chatziko** [comment]
No, in gen8 you pass `opt=1` to bypass and `opt=0` to unbypass, two different commands, and the previous state doesn't matter.

So you need to change the code, cause right now it's risky, you might call `ultrasync.unbypass` and actually do the exact opposite! I see two solutions:

Maybe there is some command that really does bypass instead of toggle, if so you might be able to find it by reverse engineering.

If not, and toggle is our only available command, the code could be modified so that it takes the current state into account. When bypass is asked:
  - if bypass is off, it calls toggle
  - if bypass is already on, it does nothing.

**Comment by thanomichalis** [comment]
As per [@flareman comment](https://github.com/caronc/ha-ultrasync/issues/23#issuecomment-1306090238) , i do believe that the data0 is sending which zone to be toggled only, nothing else.

**Comment by thanomichalis** [comment]
Also the only way to get if the bypass state is on or off, is through the bank_state, that has 14 digits. All of them can be 0 or 1 only. I have identified that the first digit of the sequence is for the Ready (0) / Not Ready (1) and the fourth is for Unbypass (0) / Bypass (1).
For example if a window is open and it is not bypassed, the bank_state is: 10000000000000
If it is open and bypassed, the bank_state is: 10010000000000

So i am not sure how to get the fourth digit and do the check.
zone.get('bank_state') is what is being used in the main.py further down for the zones, but as i said i am not very familiar with the python on how to perform that.

**Comment by thanomichalis** [comment]
With a bit further digging, i found that the `ZoneBank.UNKWN_03` defines the bypass state of the zone.

**Comment by thanomichalis** [comment]
I have put this, but although the command is sent without any error in the cmd, the bypass is doing nothing.

```
        elif self.vendor in (NX595EVendor.COMNAV):
            if self._zvbank[zone - 1] == 0:
                payload.update({
                    'comm': 82,
                    'data0': zone - 1,
                })
```

Any ideas?

**Comment by thanomichalis** [comment]
I think i got it. Currently it is working from cmd. Next step is to upload the new main.py in the HA container.
Before doing that, @chatziko and @caronc  please have a look if something doesn't make sense to you.

**Comment by thanomichalis** [comment]
I have copied to the container the updated main.py.
The strange think is that when i am sending the command through the cmd, the --bypass=1 works only if the zone is not bypassed and the --bypass=0 only if the zone is bypassed to unbypass it.
However both services 'ultrasync.bypass' and 'ultrasync.unbypass' have the same behavior, they both send the same command.
What am i missing here?

**Comment by tsotsos** [comment]
Hello, 
@thanomichalis and @caronc 

I have the same card (NX595e) and did some research a few years ago ([github.com/tsotsos/nx](https://github.com/tsotsos/nx)). However, your library seems complete with existing HA integration. But I had same problem with @thanomichalis above. So I tried this patch but it also didn't work. Then I noticed there is no update of zone "can_bypass" status for the COMNAV function. **_I might be wrong for the 'None' value but it seems to work if you assign can_bypass variable to that payload._** 

I have made a [PR](https://github.com/caronc/ultrasync/pull/26).

Feel free to ignore my PR in case you want to just add the line in your code @thanomichalis.

**Comment by caronc** [comment]
Is this good to go guys?  Should it be merged?

**Comment by tsotsos** [comment]
> Is this good to go guys? Should it be merged?

Just changed the tests and fixed a few lining issues, it works fine with NX595e I believe it can be merged.

**Comment by tsotsos** [comment]
**UPDATE**: I also verified the HA integration works without any change. both Bypass and Unbypass services now are operational with PR #26

**Comment by caronc** [comment]
Merged #26 , closing issue

**Comment by thanomichalis** [comment]
Hello...

The fixing proposed by @tsotsos was already in my implementation!
Still you can bypass the zone by calling the Unbypass service in HA. It does not solve the problem.

Furthermore, i cannot understand, where is the difference of what i tried to do (changing the "none" to "can_bypass" as i said it was already in my tests), with what you had accepted, and i tried several times to contact you (@chatziko and @caronc ) for supporting me, with zero lack apart from the initial time.

So i hope you are happy by taking others work... 
Cheers guys... Have a nice week.... 

WELL DONE but it doesn't work as i said further up...

**Pull request closed without merging**
